### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: William Moulton
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website powered by Jekyll
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: William
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: R&D Intern
# email: Your E-Mail address for the email button.
email: williamrmoulton@icloud.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: wrmoulton
linkedin_username: william-r-moulton


# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: Who Am I
# about_me_description: This will be displayed under the title.
about_me_description: "ðŸ‘‹ Hi, my name is William Moulton and Iâ€™m a senior Computer Science major based in Florida.<br><br>ðŸ§  Iâ€™m passionate about AI, machine learning, simulations, and software engineering.<br><br>ðŸ’» I love building projectsâ€”from VR applications to AI-driven systemsâ€”and constantly learning new technologies.<br><br>ðŸŽ¯ I'm set to graduate with my Bachelorâ€™s in Fall 2025 and my Masterâ€™s in 2026.<br><br>ðŸš€ Always looking for new, exciting projects to collaborate on. Feel free to reach out if you have one!<br><br>ðŸˆ Go Rams!"



# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: /Williams-Resume.pdf

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projects
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: Feel free to reach out to me!

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: wrmoulton/williammoulton.github.io
projects:
  sort_by: pushed
  exclude:
    archived: true
    projects:
      - wrmoulton
      - CS1
      - CS1V2
      - lab_6_wi472920
      - sorting
      - Lab_9
      - Lab_7
      - lab9
      - Lab_10
      - Assignment_4
      - BGA-Website
      - wordle-app
      - ADT_Demo
      - wrmoulton-oldportfolio
      - Lab9

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: ""

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
